version: '3.8'

services:
  app:
    image: laravel-vault-app
    build:
      context: ./
    container_name: laravel-app
    restart: unless-stopped
    ports:
     - "8083:8080"
    networks:
      - laravel
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: testapp
      MYSQL_USER: testuser
      MYSQL_PASSWORD: StrongPassword123!
    ports:
      - "3307:3306"
    volumes:
      - laravel_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  laravel_data:

networks:
  laravel:
    external: true
