name: Cosign Keyless Sign

on:
  workflow_dispatch:
    inputs:
      digest:
        description: "Image digest"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Image
        run: |
          cosign sign --yes "${{ github.event.inputs.digest }}"
